[sncast.default]
#accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "account-2"
url = "http://127.0.0.1:5050"
#url = "https://starknet-sepolia.infura.io/v3/3f29c2d887c540db95e4162aad10c430"

[profile.default]
url = "http://127.0.0.1:5050"
#url = "https://starknet-sepolia.infura.io/v3/3f29c2d887c540db95e4162aad10c430"
account = "account-2"

#[accounts.local_account]
#address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
#private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"